import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import RootProvider from "@/provider/root-provider";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <RootProvider>
          <Header />
          <main className="flex-1 min-h-full relative">{children}</main>
          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
